### ISSUE TITLE
19. As a service user I want to produce a report listing all the capital cities in a region organised by largest to smallest

### ISSUE THREAD

**Issue by rob-maclean** [40338732/CourseWork#27]

**Comment by 40338732** [comment]
report created using // REPORT 19: All the capital cities in a region organised by largest to smallest.
    public static String getReport19()
    {
        String results = "";
        try
        {

            // SELECT STATEMENT
            String strSelect = " SELECT Region,city.Name,  city.Population  " +
                    " FROM country join city on city.ID = country.Capital " +
                    " ORDER BY Region, city.Population DESC ";

result are what is expected - Issue now closed
