### ISSUE TITLE
21. As a service user I want to produce a report listing the top N populated capital cities in a continent where N is provided by the user

### ISSUE THREAD

**Issue by rob-maclean** [40338732/CourseWork#29]

**Comment by 40338732** [comment]
Report started

**Comment by 40338732** [comment]
// REPORT 21: As a service user I want to produce a report listing the top N populated
    // capital cities in a continent where N is provided by the user

    public static String getReport21( Integer num)
    {
        String results = "";
        try
        {

            // SELECT STATEMENT
            String strSelect = " WITH RowSETS AS ( " +
                    " SELECT country.Continent , city.Name , " +
                    " city.Population, " +
                    " ROW_NUMBER() over (PARTITION BY country.Continent ORDER BY city.Population DESC) AS RowNum " +
                    " from country, city where city.CountryCode = country.Code) " +
                    " select * from RowSETS where RowNum <= " + num ;


report are expected - issues closed
