### ISSUE TITLE
25. As a service user I want to produce a report listing the population of people, people living in cities, and people not living in cities in each country

### ISSUE THREAD

**Issue by rob-maclean** [40338732/CourseWork#33]

**Comment by 40338732** [comment]
report started

**Comment by 40338732** [comment]
report created and tested

**Comment by 40338732** [comment]
// 25. As a service user I want to produce a report listing the population of people,
    // people living in cities, and people not living in cities in each country


    public static String getReport25()
    {
        String results = "";
        try
        {

            // SELECT STATEMENT
            String strSelect = "select country.Name as 'Country', SUM(city.Population) AS City , " +
                    " country.Population - SUM(city.Population) as Urban  , country.Population AS Total " +
                    " from city " +
                    " inner join country on country.Code = city.CountryCode " +
                    " where countryCode = city.CountryCode " +
                    " group by  country.Population, country.Name ";
